# Usa una imagen base de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios (ajusta si hay subcarpetas)
COPY requirements.txt /app/

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación
COPY . /app/

# Expone el puerto 3001
EXPOSE 3001

# Comando para ejecutar la app
CMD ["python", "app.py"]
