"""empty message

Revision ID: 3383be96a954
Revises: ce857be76052
Create Date: 2025-04-03 13:35:35.712664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3383be96a954'
down_revision = 'ce857be76052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('tipo_usuarios_tipo_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('tipo_usuarios_tipo_key', ['tipo'])

    # ### end Alembic commands ###
