"""Tabla tipo de archivos creada

Revision ID: 6abe494959cc
Revises: 6ad86801fea8
Create Date: 2025-04-04 13:24:53.663801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abe494959cc'
down_revision = '6ad86801fea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_archivos',
    sa.Column('id_tipo_archivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_archivo')
    )
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TipoArchivo', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tipo_archivos', ['TipoArchivo'], ['id_tipo_archivo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('TipoArchivo')

    op.drop_table('tipo_archivos')
    # ### end Alembic commands ###
