"""Agrega columna codigo productor a Usuarios

Revision ID: 6ad86801fea8
Revises: c64c2f296469
Create Date: 2025-04-04 10:29:13.214401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad86801fea8'
down_revision = 'c64c2f296469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_productor', sa.String(length=50), server_default='Sin código', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('cod_productor')

    # ### end Alembic commands ###
