"""inicializando la base de datos

Revision ID: ce857be76052
Revises: 
Create Date: 2025-04-03 09:14:40.265423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce857be76052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_usuarios',
    sa.Column('id_tipo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_us', sa.String(length=100), nullable=False),
    sa.Column('pass_us', sa.String(length=255), nullable=False),
    sa.Column('tipo_us', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_us'], ['tipo_usuarios.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nom_us')
    )
    op.create_table('kml',
    sa.Column('id_kml', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('poligono', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('us_asociado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['us_asociado'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_kml')
    )
    op.create_table('kml_taipas',
    sa.Column('id_kml_taipas', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('us_asociado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['us_asociado'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_kml_taipas')
    )
    op.create_table('archivos',
    sa.Column('id_archivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('ruta_descarga', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('us_asociado', sa.Integer(), nullable=False),
    sa.Column('kml_asociado', sa.Integer(), nullable=True),
    sa.Column('kml_taipas_asociado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kml_asociado'], ['kml.id_kml'], ),
    sa.ForeignKeyConstraint(['kml_taipas_asociado'], ['kml_taipas.id_kml_taipas'], ),
    sa.ForeignKeyConstraint(['us_asociado'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_archivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivos')
    op.drop_table('kml_taipas')
    op.drop_table('kml')
    op.drop_table('usuarios')
    op.drop_table('tipo_usuarios')
    # ### end Alembic commands ###
